CookDelicious/CookDelicious/Areas/Identity/Pages/Error.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CookDelicious.Areas.Identity.Pages
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string RequestId { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CookDelicious/CookDelicious/Controllers/BlogController.cs
using AutoMapper;
using CookDelicious.Core.Contracts.Blog;
using CookDelicious.Core.Contracts.Pageing;
using CookDelicious.Core.Models.Blog;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CookDelicious.Controllers
{
    public class BlogController : BaseController
    {
        private readonly IBlogService blogService;
        private readonly IMapper mapper;
        private readonly IPageingService pageingService;

        public BlogController(IBlogService blogService, 
            IMapper mapper,
            IPageingService pageingService)
        {
            this.blogService = blogService;
            this.mapper = mapper;
            this.pageingService = pageingService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Home(int pageNumber, string blogPostCategory = null, int? sortMonth = null)
        {
            var model = await pageingService.GetBlogHomePagedModel(pageNumber, blogPostCategory, sortMonth);

            return View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> BlogPost([FromRoute] Guid Id)
        {
            var blogPost = await blogService.GetBlogPostServiceModelById(Id);

            var blogPostrViewModel = mapper.Map<BlogPostViewModel>(blogPost);

            return View(blogPostrViewModel);
        }
    }
}

CookDelicious/CookDelicious/Controllers/ForumController.cs
using AutoMapper;
using CookDelicious.Core.Constants;
using CookDelicious.Core.Contracts.Comments;
using CookDelicious.Core.Contracts.Forum;
using CookDelicious.Core.Contracts.Pageing;
using CookDelicious.Core.Contracts.User;
using CookDelicious.Core.Models.Comments;
using CookDelicious.Core.Models.Forum;
using CookDelicious.Core.Models.Paiging;
using CookDelicious.Core.Models.Sorting;
using CookDelicious.Core.Service.Models.InputServiceModels;
using CookDelicious.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CookDelicious.Controllers
{
    public class ForumController : BaseController
    {
        private readonly IForumService forumService;
        private readonly ICommentService commentService;
        private readonly IMapper mapper;
        private readonly IPageingService pageingService;

        public ForumController(IForumService forumService, 
            ICommentService commentService,
            IMapper mapper,
            IPageingService pageingService)
        {
            this.forumService = forumService;
            this.commentService = commentService;
            this.mapper = mapper;
            this.pageingService = pageingService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Home(int pageNumber, string sortCategory = null)
        {
            var model = await pageingService.GetForumHomePagedModel(pageNumber, sortCategory);

            return View(model);
        }

        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> CreatePost()
        {
            var categories = await forumService.GetAllPostCategoryNames();

            var model = new CreatePostViewModel()
            {
                Categories = categories,
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> CreatePost(CreatePostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("_Error", PostsConstants.InvalidPostData);
            }

            var inputModel = mapper.Map<CreateForumPostInputModel>(model);

            var error = await forumService.CreatePost(inputModel, User.Identity.Name);

            if (error != null)
            {
                ViewData[MessageConstant.ErrorMessage] = error.Messages;
            }
            else
            {
                ViewData[MessageConstant.SuccessMessage] = PostsConstants.PostSuccessfullyPublished;
            }

            var categories = await forumService.GetAllPostCategoryNames();

            model.Categories = categories;

            return View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> ForumPost([FromRoute]Guid Id, int commentPage)
        {
            var forumPostViewModel = await pageingService.GetForumPostPagedModel(Id, commentPage);

            return View(forumPostViewModel);
        }

        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> DeletePost([FromRoute]Guid Id)
        {
            var IsDeleted = await forumService.DeletePost(Id);

            if (!IsDeleted)
            {
                return BadRequest(MessageConstant.DeleteFailed);
            }

            return RedirectToAction(nameof(Home));
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> PostComment([FromRoute] Guid Id, CommentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("_Error", new ErrorViewModel() { Messages = CommentConstants.CommentContentLength });
            }

            var commentInputModel = mapper.Map<PostCommentInputModel>(model);

            var error = await commentService.PostCommentForPost(Id, commentInputModel);

            if (error != null)
            {
                return View("_Error", error);
            }

            return RedirectToAction(nameof(ForumPost), new { Id = Id });
        }

        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> DeletePostComment([FromRoute] Guid Id, [FromQuery] Guid postId)
        {
            var IsDeleted = await commentService.DeletePostComment(Id);

            if (!IsDeleted)
            {
                return BadRequest(MessageConstant.DeleteFailed);
            }

            return RedirectToAction(nameof(ForumPost), new { Id = postId });
        }
    }
}

CookDelicious/CookDelicious/Controllers/RecipeController.cs
using AutoMapper;
using CookDelicious.Core.Constants;
using CookDelicious.Core.Contracts.Comments;
using CookDelicious.Core.Contracts.Common.Categories;
using CookDelicious.Core.Contracts.Pageing;
using CookDelicious.Core.Contracts.Recipes;
using CookDelicious.Core.Models.Comments;
using CookDelicious.Core.Models.Paiging;
using CookDelicious.Core.Models.Recipe;
using CookDelicious.Core.Service.Models;
using CookDelicious.Core.Service.Models.InputServiceModels;
using CookDelicious.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CookDelicious.Controllers
{
    [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
    public class RecipeController : BaseController
    {
        private readonly IRecipeService recipeService;
        private readonly ICategoryService categoryService;
        private readonly ICommentService commentService;
        private readonly IMapper mapper;
        private readonly IPageingService pageingService;

        public RecipeController(IRecipeService recipeService,
            ICategoryService categoryService,
            ICommentService commentService,
            IMapper mapper,
            IPageingService pageingService)
        {
            this.recipeService = recipeService;
            this.categoryService = categoryService;
            this.commentService = commentService;
            this.mapper = mapper;
            this.pageingService = pageingService;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> All(int pageNumber, PagingViewModel sort)
        {
            var pagingViewModel = await pageingService.GetRecipesPagedModel(pageNumber, sort);

            return View(pagingViewModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All(int pageNumber,
            [FromQuery] string dishType,
            [FromQuery] string category, 
            [FromQuery] bool dateAsc)
        {
            var pagingViewModel = await pageingService.GetRecipesPagedModel(pageNumber, dishType, category, dateAsc);

            return View(pagingViewModel);
        }

        public async Task<IActionResult> CreateRecipe([FromRoute]string Id)
        {
            var categories = await categoryService.GetAllCategoryNames();

            var model = new CreateRecipeViewModel()
            {
                Categories = categories
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRecipe(CreateRecipeViewModel model, [FromRoute] string Id)
        {
            if (!ModelState.IsValid)    
            {
                ViewData[MessageConstant.ErrorMessage] = RecipeConstants.RecipeInvalidInformation;
                return View(model);
            }

            model.AuthorId = Id;

            var createRecipeServiceModel = mapper.Map<CreateRecipeServiceModel>(model);

            var error = await recipeService.CreateRecipe(createRecipeServiceModel);

            model = mapper.Map<CreateRecipeViewModel>(createRecipeServiceModel);

            if (error.Messages != null)
            {
                ViewData[MessageConstant.ErrorMessage] = error.Messages;
                return View(model);
            }
            else
            {
                ViewData[MessageConstant.SuccessMessage] = RecipeConstants.RecipeSuccessfullyPublished;
                return View(model);
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> RecipePost([FromRoute] Guid Id, int commentPage)
        {
            var recipePostViewModel = await pageingService.GetRecipePostPagedModel(Id, commentPage);

            return View(recipePostViewModel);
        }

        public async Task<IActionResult> Rating([FromRoute] Guid Id)
        {
            var serviceModel = await recipeService.GetById(Id);

            var viewModel = mapper.Map<RatingViewModel>(serviceModel);

            ViewData[MessageConstant.WarningMessage] = RecipeConstants.RatingReferralMessage;
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Rating(RatingViewModel model)
        {
            var ratingServiceModel = mapper.Map<RatingSetServiceModel>(model);

            if (await recipeService.IsRatingSet(ratingServiceModel))
            {
                ViewData[MessageConstant.SuccessMessage] = RecipeConstants.RatingSuccesfullyRate;
            }
            else
            {
                ViewData[MessageConstant.ErrorMessage] = RecipeConstants.RatingFailedlRate;
            }

            var serviceModel = await recipeService.GetById(ratingServiceModel.Id);

            var viewModel = mapper.Map<RatingViewModel>(serviceModel);

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> PostComment([FromRoute] Guid Id, CommentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("_Error", new ErrorViewModel() { Messages = CommentConstants.CommentContentLength });
            }

            var commentServiceModel = mapper.Map<PostCommentInputModel>(model);

            var error = await commentService.PostCommentForRecipe(Id, commentServiceModel);

            if (error != null)
            {
                return View("_Error", error);
            }

            return RedirectToAction(nameof(RecipePost), new { Id = Id });
        }

        [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
        public async Task<IActionResult> DeleteRecipeComment([FromRoute] Guid Id, [FromQuery] Guid recipeId)
        {
            var IsDeleted = await commentService.DeleteRecipeComment(Id);

            if (!IsDeleted)
            {
                return BadRequest(MessageConstant.DeleteFailed);
            }

            return RedirectToAction(nameof(RecipePost), new { Id = recipeId });
        }
    }
}

CookDelicious/CookDelicious/Controllers/UserController.cs
using AutoMapper;
using CookDelicious.Core.Constants;
using CookDelicious.Core.Contracts.User;
using CookDelicious.Core.Models.User;
using CookDelicious.Core.Service.Models.InputServiceModels;
using CookDelicious.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CookDelicious.Controllers
{
    [Authorize(Roles = $"{UserConstants.Roles.Administrator}, {UserConstants.Roles.User}")]
    public class UserController : BaseController
    {
        private readonly IUserService userService;
        private readonly IMapper mapper;
        public UserController(IUserService userService, IMapper mapper)
        {
            this.userService = userService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> MyProfile()
        {
            var serviceModel = await userService.GetUserByUsername(User.Identity.Name);

            var model = mapper.Map<UserProfileViewModel>(serviceModel);

            return View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> UserProfile([FromQuery]string AuthorName)
        {
            var serviceModel = await userService.GetUserByUsername(AuthorName);

            var model = mapper.Map<UserProfileViewModel>(serviceModel);

            return View(model);
        }

        public async Task<IActionResult> EditProfile()
        {
            var serviceModel = await userService.GetUserByUsername(User.Identity.Name);

            var model = mapper.Map<UserEditProfileViewModel>(serviceModel);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(UserEditProfileViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("_Error", new ErrorViewModel() { Messages = UserConstants.EmailAndUsernameRequired});
            }

            var inputModel = mapper.Map<UserEditProfileInputModel>(model);

            if (await userService.UpdateUser(inputModel))
            {
                ViewData[MessageConstant.SuccessMessage] = MessageConstant.SuccessfulRecord;
            }
            else
            {
                ViewData[MessageConstant.ErrorMessage] = MessageConstant.OccurredError;
            }

            return View(model);
        }
    }
}

CookDelicious/CookDelicious/Views/Shared/_Error.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<link rel="stylesheet" href="~/register-form-files/css/style.css">

<body>
    <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h1>@ViewData["Title"]</h1>
                        <p>@Model.Messages</p>
                </div>
                  </div>
                 </div>
           </section>
</body>

CookDelicious/CookDelicious/Views/Shared/_Layout.cshtml
@{
	ViewData["Title"] = "CookDelicious";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<!-- Title -->
	<title>@ViewData["Title"]</title>

	<!-- Favicon -->
	<link rel="icon" href="~/img/core-img/favicon.ico">

	<!-- Core Stylesheet -->
	<link rel="stylesheet" href="~/css/style.css">
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/classy-nav.min.css">
	<link rel="stylesheet" href="~/css/custom-icon.css">
	<link rel="stylesheet" href="~/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/css/magnific-popup.css">
	<link rel="stylesheet" href="~/css/nice-select.min.css">
	<link rel="stylesheet" href="~/css/owl.carousel.min.css">
	<link rel="stylesheet" href="~/plugins/toastr/toastr.min.css">
	@await RenderSectionAsync("Scripts", required: false)
</head>

<body>

	<!-- ##### Header Area Start ##### -->
	<header class="header-area">

		<!-- Top Header Area -->
		<div class="top-header-area">
			<div class="container h-100">
				<div class="row h-100 align-items-center justify-content-between">
					<!-- Breaking News -->
					<div class="col-12 col-sm-6">
						<div class="breaking-news">
							<div id="breakingNewsTicker" class="ticker">
								<ul>
									<li><a href="/">Hello World!</a></li>
									<li><a href="/">Welcome to Cook Delicious.</a></li>
									<li><a href="/">Join our cooking community!</a></li>
								</ul>
							</div>
						</div>
					</div>

					<!-- Top Social Info -->
					<div class="col-12 col-sm-6">
						<div class="top-social-info text-right">
							<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
							<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Navbar Area -->
		<div class="delicious-main-menu">
			<div class="classy-nav-container breakpoint-off">
				<div class="container">
					<!-- Menu -->
					<nav class="classy-navbar justify-content-between" id="deliciousNav">

						<!-- Logo -->
						<a class="nav-brand" href="/"><img src="~/img/core-img/logo.png" alt=""></a>

						<!-- Navbar Toggler -->
						<div class="classy-navbar-toggler">
							<span class="navbarToggler"><span></span><span></span><span></span></span>
						</div>

						<!-- Menu -->
						<div class="classy-menu">

							<!-- close btn -->
							<div class="classycloseIcon">
								<div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
							</div>

							<!-- Nav Start -->
							<div class="classynav">
								<ul>
									@if (User.Identity.IsAuthenticated)
									{
										<li class="active">
											<a class="active" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
										</li>
										<li>
											<a class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Всички" asp-route-category="Всички">Всички Рецепти</a>
										</li>

										<li>
											<a href="/">Меню</a>
											<div class="megamenu">
												<ul class="single-mega cn-col-4">
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #36a12e" class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Аламинути" asp-route-category="Всички">Аламинути</a>
													</li>
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #36a12e" class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Предястия" asp-route-category="Всички">Предястия</a>
													</li>
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #36a12e" class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Основни ястия" asp-route-category="Всички">Основни ястия</a>
													</li>
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #36a12e" class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Десерти" asp-route-category="Всички">Десерти</a>
													</li>
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #36a12e" class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Коктейли" asp-route-category="Всички">Коктейли</a>
													</li>
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #36a12e" class="active" asp-area="" asp-controller="Product" asp-action="All">Продукти</a>
													</li>
												</ul>
												<ul class="single-mega cn-col-4">
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #1c8314" class="active" asp-area="" asp-controller="Forum" asp-action="Home">Форум</a>
													</li>
													<li style="margin: 10px">
														<a style="font-size: 25px; color: #1c8314" class="active" asp-area="" asp-controller="Blog" asp-action="Home" asp-route-pageNumber="1">Блог</a>
													</li>
												</ul>
												<div class="single-mega cn-col-4" style="width: 700px">
													<div class="receipe-slider owl-carousel">
														<a style="width: 700px; height: 300px" href="/"><img src="~/img/bg-img/bg3.jpg" alt=""></a>
														<a style="width: 700px; height: 300px" href="/"><img src="~/img/bg-img/bg2.jpg" alt=""></a>
													</div>
												</div>
											</div>
										</li>
										<li>
											<a class="active" asp-area="" asp-controller="User" asp-action="MyProfile">Моят Профил</a>
										</li>
										@if (User.IsInRole("Administrator"))
										{
											<li>
												<a class="active" asp-area="Admin" asp-controller="Home" asp-action="Index">Админ меню</a>
											</li>
										}
										<li class="active">
											<form class="active" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home")" method="post">
												<button type="submit" class="custom-button">Изход</button>
											</form>
										</li>
									}
									else
									{
										<li>
											<a class="active" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
										</li>
										<li>
											<a class="active" asp-area="" asp-controller="Recipe" asp-action="All" asp-route-dishType="Всички" asp-route-category="Всички">Всички рецепти</a>
										</li>
										<li>
											<a class="active" asp-area="" asp-controller="Blog" asp-action="Home">Блог</a>
										</li>
										<li>
											<a class="active" asp-area="" asp-controller="Forum" asp-action="Home">Форум</a>
										</li>
										<li class="active">
											<a class="active" href="/Identity/Account/Login">Вход</a>
										</li>
										<li class="active">
											<a class="active" href="/Identity/Account/Register">Регистрация</a>
										</li>
									}
								</ul>
							</div>
							<!-- Nav End -->
						</div>
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- ##### Header Area End ##### -->
	@RenderBody()
	<!-- ##### Footer Area Start ##### -->
	<footer class="footer-area">
		<div class="container h-100">
			<div class="row h-100">
				<div class="col-12 h-100 d-flex flex-wrap align-items-center justify-content-between">
					<!-- Footer Social Info -->
					<div class="footer-social-info text-right">
						<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
						<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
					</div>
					<!-- Footer Logo -->
					<div class="footer-logo">
						<a href="/"><img src="~/img/core-img/logo.png" alt=""></a>
					</div>
					<p>
						Copyright & copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
					</p>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>
<!-- jQuery -->
<script src="~/js/jquery/jquery-2.2.4.min.js"></script>
<script src="~/js/bootstrap/popper.min.js"></script>
<script src="~/js/bootstrap/bootstrap.min.js"></script>
<script src="~/js/plugins/plugins.js"></script>
<script src="~/js/active.js"></script>

<script src="~/plugins/toastr/toastr.min.js"></script>

<partial name="_UserMessages" />
@await RenderSectionAsync("Scripts", required: false)

CookDelicious/CookDelicious/Views/Shared/_UserMessages.cshtml
@using CookDelicious.Core.Constants



@if (ViewData[MessageConstant.ErrorMessage] != null){
	<script>
		$(function() {
			toastr.error('@ViewData[MessageConstant.ErrorMessage]?.ToString()')
		});
	</script>
}

@if (ViewData[MessageConstant.WarningMessage] != null){
	<script>
		$(function() {
			toastr.warning('@ViewData[MessageConstant.WarningMessage]?.ToString()')
		});
	</script>
}

@if (ViewData[MessageConstant.SuccessMessage] != null){
	<script>
		$(function() {
			toastr.success('@ViewData[MessageConstant.SuccessMessage]?.ToString()')
		});
	</script>
}

@if (TempData[MessageConstant.SuccessMessage] != null){
	<script>
		$(function() {
			toastr.success('@TempData[MessageConstant.SuccessMessage]?.ToString()')
		});
	</script>
}